### PR TITLE
Sort workspaces by their number

### PR DESCRIPTION
**Pull request by orestisfl**
Makes the labels of the workspaces with smaller numbers the first letters of the alphabet.

### CODE REVIEW

**Review by cornerman — APPROVED** [review]
Nice, thank you!

**Comment by orestisfl** [comment]
It could also be possible to sort based on position:

https://github.com/orestisf1993/i3-easyfocus/tree/sort-outputs

I am not sure what I prefer right now but tell me if you would like something like this merged. We could add a new option.

**Comment by cornerman** [comment]
Interesting idea. For my setup it does not make a difference to sort via workspace number or position, but the position might be the more sensible default.

Though, I do not think that the euclidean distance is a good measure here. Maybe more like reading from left to right and row by row? But this also depends on the culture.

**Comment by orestisfl** [comment]
I agree with the euclidean distance because it was a bit of a brain fart. I wanted to account for exotic setups, eg:

2018-03-20-193408_455x225_escrotum

In this case I think the sensible behaviour would be the left screen first and right one after and in this one:

2018-03-20-193554_255x270_escrotum

the top screen should be first and the bottom one after.

The brain fart part is because I didn't realise that the order would be:
```
A | C
-----
B | D
```
for widescreen monitors.

We could have a heuristic like `3*(y1-y2) + (x1-x2)`.

**Comment by cornerman** [comment]
> We could have a heuristic like 3*(y1-y2) + (x1-x2).

Hmm, this could become a problem for more or wider screens. How about we replace `3` with the `<highest x-coordinate>` in the monitor layout (see `*` below)? Thereby effectively chaining the monitor rows.

A | B
C | D | E *
F

Don't know whether overlapping screens are a thing and should be handled :)

**Comment by orestisfl** [comment]
This is equivalent to a strict left to right and row by row (which is easy and not that bad for a general case):

x_max >= abs(x1 - x2). If y1 != y2 then abs(y1 - y2) * x_max >= abs(x1 - x2). Therefore, the result (positive/negative) only depends on the sign of (y1-y2) unless if y1 == y2 then it is sign(x1 - x2).

**Pull request merged**
